name: device_frame
description: Mockups for common devices.
version: 0.4.2
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_svg: ^0.22.0
  path_drawing: ^0.5.1
  freezed_annotation: ^0.14.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.2
  freezed: ^0.14.2
  pedantic: ^1.9.0
  xml: ^5.0.0